### ISSUE TITLE
Line 51

### ISSUE THREAD

**Issue by kkk-alt** [Grigorich-JSDio/TG-Parser#1]
if os.path.exists(f'../Чаты') is False:
        os . mkdir ( f '../ Chat' )
    if os.path.exists(f'../Каналы') is False:
        os . mkdir ( f '../ Channels' )
    if os.path.exists(f'../{channel_type}/{title}') is False:
        os.mkdir(f'../{channel_type}/{title}')
    with open(f'../{channel_type}/{title}/Участники {title}.json', 'w', encoding='utf8') as f:
        with open(f'../{channel_type}/{title}/Участники {title}.txt', 'w', encoding='utf8') as file:
            all_users = {
                'admins': admins,
                'users': members

-----------------------------------------------------------------------------------------------
Syntax errors detected :

Line 51:
if os.path.exists(f'../\u0427\u0430\u0442\u044b') is False:
^
SyntaxError: invalid syntax

**Comment by Grigorich-JSDio** [comment]
Возможно, проблема в локалях системы? попробуйте установить русскую локаль командой dpkg-reconfigure locales
