### ISSUE TITLE
'Non type'

### ISSUE THREAD

**Issue by onikonov** [Grigorich-JSDio/TG-Parser#4]
'Non type' object is not mapping 
![image](https://user-images.githubusercontent.com/20572937/153220321-dde28551-9e6a-43bb-9b43-b6e6ca786245.png)

**Comment by Grigorich-JSDio** [comment]
> 'Non type' object is not mapping ![image](https://user-images.githubusercontent.com/20572937/153220321-dde28551-9e6a-43bb-9b43-b6e6ca786245.png)

Исправлено.
